# Server configuration
server:
  context-path: /micro
  port: 8080

# Spring properties
spring:
  application:
     name: customer-microservice

     cloudant:
        username: username
        password: password
        host: host
        protocol: https
        port: 1234
        database: customers

jwt:
  enabled: false
  key: short_key
        